__version__ = "0.2.1"
__author__ = "Nabil-Fareed Alikhan"
__email__ = "nabil@happykhan.com"
__license__ = "GPLv3"
__description__ = "A bioinformatics software focused on quality control based on species criteria"
__name__ = "speccheck"
