name: CI - build docker image via python

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write   # required if you want to push to GHCR using GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for buildx multi-arch support)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # if you need to push to GHCR, login first (see below)
      - name: Login to GitHub Container Registry
        if: ${{ secrets.GITHUB_TOKEN != '' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: pip install --upgrade pip && pip install -r requirements.txt || true

      - name: Run Python build script
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/my-image
          IMAGE_TAG: ${{ github.sha }}
        run: python docker/build_docker.py
