name: CI - build docker image via python

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write   # required if you want to push to GHCR using GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for buildx multi-arch support)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    # login to Docker Hub before pushing
    - name: Login to Docker Hub
      if: ${{ secrets.DOCKER_USERNAME != '' }}
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: pip install --upgrade pip && pip install -r requirements.txt || true

      - name: Run Python build script
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: python docker/build_docker.py
